BEST_CKPT: /home/tien/paindiffusion/checkpoints/flow_matching-epoch=17-train_loss=0.04.ckpt
DATASET:
  batch_size: 40
  img_size: 256
  is_video: true
  load_3d_latents: true
  load_au_features: false
  load_emotion_labels: true
  load_frame: false
  load_pspi_no_au43: true
  load_stimulus_label: true
  load_stimulus_values: true
  max_length: 64
  num_workers: 26
  path_to_3d_latents: /media/tien/SSD-NOT-OS/pain_intermediate_data/emoca_latent_code/
  path_to_frame_labels: /media/tien/SSD-NOT-OS/pain_intermediate_data/processed_pain_data_no_facedetector/
  path_to_video_frame: /media/tien/SSD-DATA/data/BioVid HeatPain DB/PartC/extracted_frame/
  test_batch_size: 1
  test_max_length: 64
  train_shuffle: true
  val_batch_size: 1
  val_max_length: 640
  val_shuffle: false
DATA_STATS:
  emotion:
    mean: 4.6183
    std: 1.3559
  expressiveness:
    mean: 8.33
    std: 0.674
  stimulus_abs:
    mean: 37.2281
    std: 7.0676
DIFFUSION:
  guide:
  - 1.0
  - 1.0
  - 1.0
LAST_CKPT: /home/tien/paindiffusion/checkpoints/last-v1.ckpt
MODEL:
  attn_dim_head: 32
  attn_heads: 4
  channels: 4
  context_channels: 12
  context_dim: 128
  dim: 32
  dim_mults:
  - 1
  - 2
  - 4
  - 8
  dropout: 0
  learned_variance: false
  self_condition: false
  sinusoidal_pos_emb_theta: 10000
  type: video
